### ISSUE TITLE
SQLite tables get created correctly but are empty

### ISSUE THREAD

**Issue by g1sbi** [Gobluebro/Geekhack-scraper#27]
I'm trying to set up a local database for testing the scraper. I made a `scraper.db` file, images/ folder in the root of the project and filled the .env with this data:
```
SERVER_PORT=8091
DB_TYPE=sqlite
DB_NAME=scraper.db
DB_HOST=
DB_PORT=
DB_USER=
DB_PASS=
DB_DIALECT=sqlite
IMAGES_PATH=images/
```
but when I run `npm run scrape` I get:
```
❯ npm run scrape

> geekhack-scraper@1.1.4 scrape
> ts-node ./geekhack-scraper/index.ts

Database error: ConnectionError [SequelizeConnectionError]: SQLITE_CANTOPEN: unable to open database file
    at Database.<anonymous> (/home/gisbi/code/thock/scraper/node_modules/sequelize/src/dialects/sqlite/connection-manager.js:78:34) {
  parent: [Error: SQLITE_CANTOPEN: unable to open database file] {
    errno: 14,
    code: 'SQLITE_CANTOPEN'
  },
  original: [Error: SQLITE_CANTOPEN: unable to open database file] {
    errno: 14,
    code: 'SQLITE_CANTOPEN'
  }
}
```

what am I doing wrong? Thanks in advance. 

EDIT: I solved this problem by modifying the `initdb.ts` file like this:

```
import { Sequelize, Dialect } from "sequelize";
import { Environment } from "../utils/constants";

const init = new Sequelize("", "", "", {
  dialect: Environment.dbDialect as Dialect,
  storage: Environment.dbName,
});

export default init;
````

Now the connection happens and the tables are created correctly. However, even while the scraping happens, they remain empty.

**Comment by Gobluebro** [comment]
Hey there,

I use a running postgress database by making a connection to it with the 

```
DB_HOST=
DB_PORT=
DB_USER=
DB_PASS=
```

all filled out so I'm not sure how to help with this problem. Have you checked the [sequelize documentation](https://sequelize.org/docs/v6/getting-started/)?

**Comment by g1sbi** [comment]
Sorry, I didn't know how the scraping process worked. I just realized that the scraper downloads all images first and then updates the database. I let it go and it successfully stored everything. Awesome tool btw, thank you!

**Comment by Gobluebro** [comment]
> Sorry, I didn't know how the scraping process worked. I just realized that the scraper downloads all images first and then updates the database. I let it go and it successfully stored everything. Awesome tool btw, thank you!

Glad everything worked out 👍
